### ISSUE TITLE
e-up control climate

### ISSUE THREAD

**Issue by andlo** [enoch85/ovms-home-assistant#116]
It seems that I can turn off climate bu isue action
```
action: ovms.control_climate
data:
  vehicle_id: e-up
  hvac_mode: "off"
  temperature: 30
  duration: 10
```
But I cant turn on by issue action
```
action: ovms.control_climate
data:
  vehicle_id: e-up
  hvac_mode: "heat"
  temperature: 30
  duration: 10
```
It does howver worm in the OVMS app

In the MQTT i see this error
ovms/e-up/client/rr/response/bb6d08ce
```
Unrecognised command
Usage: climatecontrol off|on
```

Turning on and of charging works :)

**Comment by andlo** [comment]
Could be related to #111

**Comment by andlo** [comment]
I canturn onclimate by sending command 

```
action: ovms.send_command
data:
  vehicle_id: e-up
  command: climate on
```
